language: scala
sudo: required
dist: trusty
env:
  global:
    - _JAVA_OPTIONS="-Xmx1500m -XX:MaxPermSize=512m -Dakka.test.timefactor=3"
    - SPARK_HOME=/tmp/spark-2.0.0-bin-hadoop2.7
scala:
   - 2.11.8
jdk:
   - oraclejdk8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install python3 python3-pip
  - ci/install-python-dependencies.sh
  - ci/install-spark.sh
script:
  - sbt clean coverage testPython test coverageReport
  - find job-server-python/src/python -name *.py -exec pep8 {} +
after_success:
  - bash <(curl -s https://codecov.io/bash)
